//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SalaryCalculator_et {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SalaryCalculator_et() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Resources.Pages.SalaryCalculator.et", typeof(SalaryCalculator_et).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brutopalk.
        /// </summary>
        internal static string GrossSalary {
            get {
                return ResourceManager.GetString("GrossSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tulumaks.
        /// </summary>
        internal static string IncomeTax {
            get {
                return ResourceManager.GetString("IncomeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netopalk.
        /// </summary>
        internal static string NetSalary {
            get {
                return ResourceManager.GetString("NetSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kogumispension (II sammas).
        /// </summary>
        internal static string PensionSecondPillar {
            get {
                return ResourceManager.GetString("PensionSecondPillar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palgakalkulaator.
        /// </summary>
        internal static string SalaryCalculatorName {
            get {
                return ResourceManager.GetString("SalaryCalculatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sotisaalmaks.
        /// </summary>
        internal static string SocialTax {
            get {
                return ResourceManager.GetString("SocialTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Töötuskindlustusmakse (töötaja).
        /// </summary>
        internal static string UnemploymentInsuranceEmployee {
            get {
                return ResourceManager.GetString("UnemploymentInsuranceEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Töötuskindlustusmakse (tööandja).
        /// </summary>
        internal static string UnemploymentInsuranceEmployer {
            get {
                return ResourceManager.GetString("UnemploymentInsuranceEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tööandja kulu.
        /// </summary>
        internal static string WageFund {
            get {
                return ResourceManager.GetString("WageFund", resourceCulture);
            }
        }
    }
}
