name: Build and Commit

# Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: write
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup latest .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Publish .NET Project
        run: dotnet publish WebUI/WebUI.csproj -c:Release -p:GHPages=true -o dist/Web --nologo

      # base href url value of index should be changed so that resources like CSS and scripts can load properly. 
      - name: Rewrite base href
        if: success()
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1.1.0
        with:
          html_path: dist/Web/wwwroot/index.html
          base_href: '/'
      
      # base href url value of 404 should be changed so static pages would redirect correctly 
      - name: Rewrite base href
        if: success()
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1.1.0
        with:
          html_path: dist/Web/wwwroot/404.html
          base_href: '/'

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/Web/wwwroot
